### ISSUE TITLE
Fault in documentation of CpnetSerialServer

### ISSUE THREAD

**Issue by wahlm** [durgadas311/cpnet-z80#21]
First many thanks for the CP/M 3 porting of CP/NET. I just adapted it to the hardware of my old homebrew Z80 system. As I have chosen to use the ser-dri protocol on client side, I fell over a fault in the CpnetSerialServer documentation. As described there I defined "cpnet_proto = DRI" in the configuration file. No chance to get it running that way! The needed and correct parameter is "cpnet_protocol" and not the abbreviated one. Using this, connection and file transfer are working perfectly.

It would have been much easier to find out if the java sourcecode would have been available somewhere. I searched for it without success. If it is really not available, Is there any chance to release it?

**Comment by durgadas311** [comment]
Sorry about the typo, I have fixed that now and checked for any other misspelled properties. Thanks for notifying me.

Regarding source code, I have not released it yet because it shares a lot of common files with other projects and I haven't yet got a good scheme for sharing the code between projects. Still working on that. It is available as a tar-gz as part of the H89 simulator at http://sebhc.durgadas.com/mms89/v89.tgz
