### ISSUE TITLE
Build problem....

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#23]
It's been a while since I have tried to build the cpnet code.
Did a fresh pull and created all the tools needed.

make NIC=w5500 HBA=mt011
vcpm mac "netstat.asm" '$SZLL'
Creating HostFileBdos 00 device with root dir /home/ubuntu/HostFileBdos
D>mac netstat.asm $SZLL
Undefined Output on port 25e value 20
Undefined Output on port 25e value 20
Undefined Output on port 35c value 03
Undefined Output on port 5c value 00
Undefined Output on port 5c value 00
Undefined Output on port ff5c value ff
Undefined Input on port ff5c

**Comment by durgadas311** [comment]
This is working fine for me. Could your MAC.COM have gotten corrupted? Those errors are typically because the CP/M program (MAC.COM in this case) has crashed.

I saw errors like these when using M80/L80 to link a ROM image (orged at 0000), if I selected the L80 option which causes the ROM image to overwrite CP/M at 0000. In other words, I had crashed L80 by doing that.

**Comment by jayacotton** [comment]
Well, turns out that I have the wrong version of mac.com
